<main>
    <div class="main-profil">
        <div class="card">
            <div class="card-body">
                <img class="image-profil img-fluid" src="./assets/images/photoAntoinePlage.JPG" alt="photo de Antoine Huet">
                <p>Jeune Dévloppeur Web spécialiser en back-end, on me décrit souvent comme assidu, Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde voluptas corporis neque dolorum nisi autem sunt sed amet fugit esse ab, distinctio, architecto vitae adipisci reiciendis fugiat odio eaque totam cumque blanditiis quaerat. Deleniti tenetur aliquam cum dolorum voluptatibus expedita eos officiis cumque eveniet, perferendis incidunt cupiditate hic reiciendis sed natus iste veritatis repellendus impedit nesciunt odit ea nisi vel. Nesciunt voluptates esse, consequatur temporibus atque natus similique sint vitae inventore facilis itaque illum numquam iste deleniti dolores! Sunt et, repellendus recusandae itaque sapiente animi nulla ipsum ipsa vel tenetur? Dignissimos, id, sunt sit voluptatem, quaerat dolorum similique excepturi sapiente neque possimus distinctio. Aliquid aliquam blanditiis maxime inventore consequuntur reiciendis explicabo atque, nemo harum maiores dolore, quam officia perferendis rerum adipisci ipsa! Tenetur dolorem ut quasi, id, itaque consectetur animi eligendi tempora reprehenderit dignissimos asperiores odit est doloribus nihil aliquam unde eaque laudantium enim ex? Corporis, laboriosam dignissimos? Odit odio magni ad inventore saepe quidem quis aliquam libero veritatis repudiandae perspiciatis totam hic cupiditate doloribus at ipsam ipsum, cum quas? Minus aliquam vero nulla magnam, facilis explicabo nesciunt laborum tempora mollitia blanditiis asperiores odio ea tenetur. Ipsam, similique assumenda ex architecto repudiandae, inventore alias optio officiis quas, aliquid asperiores nam impedit earum unde veniam eveniet facilis. Est fuga et, sit quisquam blanditiis maiores neque? Recusandae perspiciatis dolorum at laboriosam asperiores fugit temporibus autem magnam nobis, iusto incidunt magni dicta. Iure, iusto doloribus, explicabo voluptate consectetur eveniet cumque voluptatibus, pariatur similique perferendis quod nisi laborum illum nemo laboriosam? Molestias reprehenderit eaque, provident placeat delectus vitae dolorem atque est eveniet enim pariatur, rem obcaecati, aliquid qui officia libero quas dolorum consequuntur? Ex velit magnam quisquam accusantium nostrum veniam ipsum aut neque vel rem ullam aliquid non minus officia fugit perspiciatis enim facilis, perferendis consequuntur modi esse nihil! Fugit neque mollitia quo voluptate.
                </p>
            </div>    
        </div>
    </div>
</main>